<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationTitle>أذكار اليوم</ApplicationTitle>
    <AssemblyName>AthkarAlyawm</AssemblyName>
    <RootNamespace>Athkar</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="..\..\data\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>data\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Content>
  </ItemGroup>
</Project>
